### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by parhelium** [bestguy/generator-ractive-webpack#1]
```
➜  ~ yo ractive-webpack
/Users/me/.nvm/versions/v5.5.0/lib/node_modules/generator-ractive-webpack/utils/yeoman.js:20
const getAppName = (appName = getBaseDir()) => _.slugify(_.humanize(appName));
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/me/.nvm/versions/v5.5.0/lib/node_modules/generator-ractive-webpack/generators/app/prompts.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

<img width="1042" alt="screen shot 2016-07-25 at 11 22 12" src="https://cloud.githubusercontent.com/assets/725686/17096534/19a292a4-525a-11e6-9fa5-6371e7d010b5.png">

**Comment by bestguy** [comment]
Thanks for the heads up, will take a look via nvm tonight, seems fine on node 6.2.x

**Comment by bestguy** [comment]
This should be fixed on Node 4.x in version 0.1.1: https://github.com/bestguy/generator-ractive-webpack/commit/a4d962a504010e108978572256f8c6e0fdbf9e13

Let me know if this works for you or if you see any issues.

**Comment by bestguy** [comment]
@parhelium will close for now, let me know if you see issues with latest.
